redis = (loadfile "redis.lua")()
io.write("ای دی ربات را وارد کنید : ")
local last = io.read()
io.write("\nای دی عددی مدیر را وارد کنید : ")
local sudo=io.read()
local text,ok = io.open("base.lua",'r'):read('*a'):gsub("TABCHI%-ID",last)
io.open("tabchi-"..last..".lua",'w'):write(text):close()
io.open("tabchi-"..last..".sh",'w'):write("while true; do\n./telegram-cli-1222 -p tabchi-"..last.." -s tabchi-"..last..".lua\ndone"):close()
io.popen("chmod 777 tabchi-"..last..".sh")
redis:set('tabchi:'..last..':fullsudo',sudo)
print("تمام!\nربات جدید ساخته شد...\nID : "..last.."\nمدیر : "..sudo.."\nاجرا : ./tabchi-"..last..".sh")
